# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import addcomment_pb2 as addcomment__pb2


class addcommentStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addcomment = channel.unary_unary(
                '/addcomment/addcomment',
                request_serializer=addcomment__pb2.input.SerializeToString,
                response_deserializer=addcomment__pb2.output.FromString,
                )


class addcommentServicer(object):
    """Missing associated documentation comment in .proto file"""

    def addcomment(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_addcommentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addcomment': grpc.unary_unary_rpc_method_handler(
                    servicer.addcomment,
                    request_deserializer=addcomment__pb2.input.FromString,
                    response_serializer=addcomment__pb2.output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'addcomment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class addcomment(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def addcomment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/addcomment/addcomment',
            addcomment__pb2.input.SerializeToString,
            addcomment__pb2.output.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
