# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import addreply_pb2 as addreply__pb2


class addreplyStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addreply = channel.unary_unary(
                '/addreply/addreply',
                request_serializer=addreply__pb2.input.SerializeToString,
                response_deserializer=addreply__pb2.output.FromString,
                )


class addreplyServicer(object):
    """Missing associated documentation comment in .proto file"""

    def addreply(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_addreplyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addreply': grpc.unary_unary_rpc_method_handler(
                    servicer.addreply,
                    request_deserializer=addreply__pb2.input.FromString,
                    response_serializer=addreply__pb2.output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'addreply', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class addreply(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def addreply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/addreply/addreply',
            addreply__pb2.input.SerializeToString,
            addreply__pb2.output.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
