# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import getcomments_pb2 as getcomments__pb2


class getcommentsStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getcomments = channel.unary_unary(
                '/getcomments/getcomments',
                request_serializer=getcomments__pb2.input.SerializeToString,
                response_deserializer=getcomments__pb2.output.FromString,
                )


class getcommentsServicer(object):
    """Missing associated documentation comment in .proto file"""

    def getcomments(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_getcommentsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getcomments': grpc.unary_unary_rpc_method_handler(
                    servicer.getcomments,
                    request_deserializer=getcomments__pb2.input.FromString,
                    response_serializer=getcomments__pb2.output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'getcomments', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class getcomments(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def getcomments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/getcomments/getcomments',
            getcomments__pb2.input.SerializeToString,
            getcomments__pb2.output.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
