# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import getreplied_pb2 as getreplied__pb2


class getrepliedStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getreplied = channel.unary_unary(
                '/getreplied/getreplied',
                request_serializer=getreplied__pb2.input.SerializeToString,
                response_deserializer=getreplied__pb2.output.FromString,
                )


class getrepliedServicer(object):
    """Missing associated documentation comment in .proto file"""

    def getreplied(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_getrepliedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getreplied': grpc.unary_unary_rpc_method_handler(
                    servicer.getreplied,
                    request_deserializer=getreplied__pb2.input.FromString,
                    response_serializer=getreplied__pb2.output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'getreplied', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class getreplied(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def getreplied(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/getreplied/getreplied',
            getreplied__pb2.input.SerializeToString,
            getreplied__pb2.output.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
