# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import like_pb2 as like__pb2


class likeStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.like = channel.unary_unary(
                '/like/like',
                request_serializer=like__pb2.input.SerializeToString,
                response_deserializer=like__pb2.output.FromString,
                )


class likeServicer(object):
    """Missing associated documentation comment in .proto file"""

    def like(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_likeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'like': grpc.unary_unary_rpc_method_handler(
                    servicer.like,
                    request_deserializer=like__pb2.input.FromString,
                    response_serializer=like__pb2.output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'like', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class like(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def like(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/like/like',
            like__pb2.input.SerializeToString,
            like__pb2.output.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
