# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import removecomment_pb2 as removecomment__pb2


class removecommentStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.removecomment = channel.unary_unary(
                '/removecomment/removecomment',
                request_serializer=removecomment__pb2.input.SerializeToString,
                response_deserializer=removecomment__pb2.output.FromString,
                )


class removecommentServicer(object):
    """Missing associated documentation comment in .proto file"""

    def removecomment(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_removecommentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'removecomment': grpc.unary_unary_rpc_method_handler(
                    servicer.removecomment,
                    request_deserializer=removecomment__pb2.input.FromString,
                    response_serializer=removecomment__pb2.output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'removecomment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class removecomment(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def removecomment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/removecomment/removecomment',
            removecomment__pb2.input.SerializeToString,
            removecomment__pb2.output.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
