# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import removereply_pb2 as removereply__pb2


class removereplyStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.removereply = channel.unary_unary(
                '/removereply/removereply',
                request_serializer=removereply__pb2.input.SerializeToString,
                response_deserializer=removereply__pb2.output.FromString,
                )


class removereplyServicer(object):
    """Missing associated documentation comment in .proto file"""

    def removereply(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_removereplyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'removereply': grpc.unary_unary_rpc_method_handler(
                    servicer.removereply,
                    request_deserializer=removereply__pb2.input.FromString,
                    response_serializer=removereply__pb2.output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'removereply', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class removereply(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def removereply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/removereply/removereply',
            removereply__pb2.input.SerializeToString,
            removereply__pb2.output.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
