# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import click_news_pb2 as click__news__pb2


class click_newsStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.click_news = channel.unary_unary(
                '/click_news/click_news',
                request_serializer=click__news__pb2.input.SerializeToString,
                response_deserializer=click__news__pb2.output.FromString,
                )


class click_newsServicer(object):
    """Missing associated documentation comment in .proto file"""

    def click_news(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_click_newsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'click_news': grpc.unary_unary_rpc_method_handler(
                    servicer.click_news,
                    request_deserializer=click__news__pb2.input.FromString,
                    response_serializer=click__news__pb2.output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'click_news', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class click_news(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def click_news(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/click_news/click_news',
            click__news__pb2.input.SerializeToString,
            click__news__pb2.output.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
